# Generated by Django 5.1.1 on 2024-09-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name': 'Экспонат', 'verbose_name_plural': 'Экспонаты'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.author'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.collection'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.hall'),
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibits',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibits',
            field=models.ManyToManyField(related_name='exhibitions', to='museum.exhibit'),
        ),
    ]
