# Generated by Django 5.1.1 on 2024-10-15 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_exhibit_options_alter_exhibit_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='picture',
            field=models.ImageField(null=True, upload_to='exhibits', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.hall', verbose_name='Холл'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='exhibits',
            field=models.ManyToManyField(related_name='exhibitions', to='museum.exhibit', verbose_name='Экспонаты'),
        ),
    ]
