# Generated by Django 5.1.1 on 2024-10-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_exhibit_picture_alter_exhibit_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='picture',
        ),
    ]
