# Generated by Django 5.1.1 on 2024-10-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_remove_exhibit_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='picture',
            field=models.ImageField(null=True, upload_to='exhibits', verbose_name='Изображение'),
        ),
    ]
