# Generated by Django 5.1.1 on 2024-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_exhibit_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='authors', verbose_name='Изображение'),
        ),
    ]
