# Generated by Django 5.1.1 on 2024-10-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_author_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='deathdate',
            field=models.DateField(null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='cost',
            field=models.TextField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='creation_year',
            field=models.IntegerField(null=True, verbose_name='Год создания'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='museum.hall', verbose_name='Холл'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='closing_date',
            field=models.DateField(null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='exhibits',
            field=models.ManyToManyField(null=True, related_name='exhibitions', to='museum.exhibit', verbose_name='Экспонаты'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='opening_date',
            field=models.DateField(null=True, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='location',
            field=models.TextField(null=True, verbose_name='Местоположение'),
        ),
    ]
