# Generated by Django 5.1.1 on 2024-10-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_alter_author_birthdate_alter_author_deathdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='authors', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='exhibits', verbose_name='Изображение'),
        ),
    ]
