# Generated by Django 5.1.1 on 2024-10-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_alter_author_picture_alter_exhibit_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='authors', verbose_name='Изображение'),
        ),
    ]
