# Generated by Django 5.1.1 on 2024-11-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_alter_author_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='exhibits',
            field=models.ManyToManyField(related_name='exhibitions', to='museum.exhibit', verbose_name='Экспонаты'),
        ),
    ]
