# Generated by Django 5.1.1 on 2024-11-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_visitor_alter_exhibition_exhibits'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='exhibition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='museum.exhibition', verbose_name='Выставка'),
        ),
    ]
